{% set version = "0.9.1" %}

package:
  name: python-gist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-gist/python-gist-{{ version }}.tar.gz
  sha256: 4bf4c782a169e6771de9c996228f23b635cc7d99cf8a0502ea8cade22ff884a5

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - docopt
    - python
    - python-gnupg >=0.4.1
    - requests
    - simplejson

test:
  imports:
    - gist

about:
  home: http://github.com/jdowner/gist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Manage github gists

extra:
  recipe-maintainers:
    - ocefpaf
