{% set version = "0.9.2" %}

package:
  name: python-gist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-gist/python-gist-{{ version }}.tar.gz
  sha256: 73885ff47d6d35cd2192e8447a6acbf2572dd8187b9439bc64330824f7fa8178

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gist = gist.client:main

requirements:
  host:
    - python
    - pip
  run:
    - docopt
    - python
    - python-gnupg >=0.4.1
    - requests
    - simplejson

test:
  imports:
    - gist
  commands:
    - pip check
    - gist --help
  requires:
    - pip

about:
  home: http://github.com/jdowner/gist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Manage github gists

extra:
  recipe-maintainers:
    - ocefpaf
