{% set version = "0.10.0" %}

package:
  name: python-gist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-gist/python-gist-{{ version }}.tar.gz
  sha256: 0cce1749504a8d0fc751c2ce2cc6fb6f6f0d4d7147cfb103be83311f779a08b6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gist = gist.client:main

requirements:
  host:
    - python
    - pip
  run:
    - docopt
    - python
    - python-gnupg >=0.4.1
    - requests
    - simplejson

test:
  imports:
    - gist
  commands:
    - pip check
    - gist --help
  requires:
    - pip

about:
  home: http://github.com/jdowner/gist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Manage github gists

extra:
  recipe-maintainers:
    - ocefpaf
