{% set version = "0.10.6" %}

package:
  name: python-gist
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-gist/python-gist-{{ version }}.tar.gz
  sha256: e9ba0ce44591564d114252a8cc073a61e6dc7304b667997af783ec581c05e19e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - gist = gist.client:main

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry
  run:
    - python >=3.6,<4.0
    - python-gnupg >=0.4.7,<0.5.0
    - requests >=2.25.1,<3.0.0
    # - docopt
    # - simplejson

test:
  imports:
    - gist
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/jdowner/gist
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Manage github gists

extra:
  recipe-maintainers:
    - ocefpaf
