travis:
  secure:
    BINSTAR_TOKEN: HTRZh0yejBpJ2PnMxd2RukCXxZ6Q/4/vUlISpLRZ341XLOFVnDVETfyx0apwFMsWpQR3a4bp29oFzoUS7v7Vm58n2FZYkhMMAlAP1t8VJUoA3eT4bfVon5HH3SwGD6KvkRRYJ+WXWCKyBuoM2PUJ4CG/0CFB7eE2bxVp1fyGwtrHYXVJCsEq5Drk5mPLxjJ9SppvfsOddK7y4U2SOi7HsjdYQnPz1lJ3x5f99BsnHSNx8lrLfNlflsivd/N0D0WBjRZ6FHjDqD4fd1NNBhGaWvnxfTvVbwk+6TKJ6CGJlDKnfsLfAQfBDf3MGY03CqrFxMt4G3IjzdinITmy9+alqU40jgHqcXb2V9qaEigarxMV4Aww/GbeWfh6K6PqQCdV8y/9U/0vGfVLBEDJRW7+hbe5OO8k0aYFzGff3Dqd1usHzfuaVypYP10dC9ThzN8uIIDk/QxZzVcn4k2JbOhTWZP+LD4ccpVs4HMpgzW3dIgHfeFbXfBQI8lfX2JE5/B9Wuwuri3iXplblbk7sDq505727GQijWgyqMhY7DvPVZpYlGV6A0trQjZ5jHcxgusV0SgMbPRc/hMb2I6Tbvdmww1GHUcptcF5UesE7SMV0dDR9m49+ockSESRtKMug1LoFYXZNJhaN25xx+IUL4Yekz9YZbmNuB4YU/NSflsdWos=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
